Gustavodev
oresat/oresat-helmholtz pull request #15
Opened 2023-09-03 23:26 UTC by gcotom

Created a shell for the HC that controls HC power supplies and the H-Bridges w/ a Arduino Nano.

2023-11-08 02:06 UTC, dmitri-mcguckin requested changes
In general looks good.

Please merge in your `oresat_helmholtz` python module to the `src/` directory so we can utilize the `setuptools` project and make this into an installable python app.

2023-11-08 02:06 UTC, dmitri-mcguckin commented on oresat_helmholtz/ZXY6005s.py
> +#Copy of ZXY6005s library.
This file seems to contain all of the same changes already seen in PR #14. Is this accurate?

If so, then we can omit it from this PR.

2023-11-08 02:06 UTC, dmitri-mcguckin commented on oresat_helmholtz/__main__.py
> +    parser.add_argument('-l', '--arduino-location', help='Location to Arduino. ')
I would recommend the verbiage: `arduino-device` here and in similar situations.

2023-11-08 02:06 UTC, dmitri-mcguckin commented on Arduino_Comms/PSAS_HHCage/PSAS_HHCage.ino
> +    digitalWrite(xina,LOW);
For this and similar situations. I would recommend abstracting this to either a static function or some kind of variable-fed function such as:


```c++
static void write(const byte[] write_bytestring, byte*& result) {
   // Conditionally set bits based on the bytestring here
   
   // load result so we can verify the bits were set
}
```

This can help separate code so it improves readability and leave a hook for unit-testing.

2023-11-08 02:06 UTC, dmitri-mcguckin commented on command_line.py
> +if __name__ == "__main__":
Is this file intended to be the entry point? If so, why here and not `__main__` ?

2023-11-08 02:06 UTC, dmitri-mcguckin commented on Arduino_Comms/PSAS_HHCage/PSAS_HHCage.ino
> +  if (Serial.available() > 0) {
While single-char commands are technically fine, it might be helpful to future you, *( as well as any future developers)*, to actually expand these to human-readable command strings.

This would lend itself to opening up a telnet client to the arduino for manual testing which allows you to develop this apart from the python client.

2023-11-08 02:06 UTC, dmitri-mcguckin commented on oresat_helmholtz/Arduino.py
> +class Arduino:
I recommend adding docstrings here and for all similar class definitions:

```python
class Arduino:
    '''
    A short description of what this class does
    
    :param param1: Description of param1
    '''
```

2023-11-08 02:06 UTC, dmitri-mcguckin commented on oresat_helmholtz/Arduino.py
> +    def __init__(self, location: str):
See other comment in `main()`: prefer verbiage `device` over `location`.

2023-11-08 02:06 UTC, dmitri-mcguckin commented on oresat_helmholtz/Arduino.py
> +        for i in serial.tools.list_ports.comports():
I recommend generators since the python interpreter knows how to optimize these:

```python
ports = list(filter(lambda x: x.location == location,
                    serial.tools.list_ports.comports()))
serial_port = ports[0] if(len(ports) > 0) else None
```

Also lends itself to idempotent behavior a bit more.

2023-11-08 02:06 UTC, dmitri-mcguckin commented on oresat_helmholtz/Arduino.py
> +    def write_message(self, msg):
For this and similar scenarios, please add both the param type and description to the docstring of what the msg is.

Example:

```python
def write_message(self, msg: str):
    '''
    Sends a command to the arduino
    
    :param msg: A UTF-8 string to be sent to the arduino.
    '''
```

2023-11-08 02:06 UTC, dmitri-mcguckin commented on oresat_helmholtz/Arduino.py
> +    def create_command(self, command):
Excellent that you've separated this out from the actual writing of the serial channel.

Please write unit tests around this function asserting it generates the correct things, *(according to your Arduino firmware)*, or otherwise fails safely.

2023-11-08 02:06 UTC, dmitri-mcguckin commented on oresat_helmholtz/Arduino.py
> +#definitions for function that help operate the commands.
Are these intended to be private functions? If so, add `__` to the front of them.

Example:

```python
def __set_positive_x() ->str:
```

Also, please lowercase x/y/z in the names since you are using snake-case.

2023-11-08 02:06 UTC, dmitri-mcguckin commented on oresat_helmholtz/__main__.py
> +    def help_firmware(self):
If we are going the route of an interactive shell for controlling the cage, I recommend using `argparse` to handle all of the parsing-related logic.

2023-11-08 02:06 UTC, dmitri-mcguckin commented on oresat_helmholtz/__main__.py
> +    parser.add_argument('-m', '--mock', action = "store_true")
Is this mock-mode just for development purposes?

Or is there another configuration mode needed?

If just for development, I would recommend using `socat` on linux to setup a virtual serial device instead. [See man pages](https://manpages.org/socat).

Example:

```sh
socat -d -d pty,raw,echo=1 pty,raw,echo=1
```

Which opens a fake serial device at `/dev/pts/N` where N is whatever next serial number is available.

This is preferred to adding mock code to your application so you can keep the buisness logic clean and free of baked-in test code.

2023-11-08 02:06 UTC, dmitri-mcguckin commented on testmain.py
> +from zxy6005s import ZXY6005s
Is this script intended for manual-regression testing?

If so, please move it and similar scripts to a `scripts/` subdir,

2024-03-04 01:32 UTC, ashermancinelli commented
@andrewgreenberg and I decided it would be best to merge this work as-is and continue building on it. I am merging without @dmitri-mcguckin's requirements (even though I agree with them) so we can move forward.

2024-03-04 01:32 UTC, ashermancinelli commented
@andrewgreenberg and I decided it would be best to merge this work as-is and continue building on it. I am merging without @dmitri-mcguckin's requirements (even though I agree with them) so we can move forward.

2024-03-04 01:33 UTC, merged

2024-03-04 01:43 UTC, dmitri-mcguckin commented
@andrewgreenberg @ashermancinelli 

I would strongly insist that this MR got redirected to devel instead, or simply fork the `gustavodev` branch as-is if you need a working branch based off of Gustavo's last-known code.

One of the reasons the HHC repo is so thrashed right now is because we've been blindly allowing merges that- while functionally complete still need cleanup and ample testing- so `main` should be gated. A `devel`  branch on the other hand, you are free to do whatever you like in- including the much-needed  cleanup.

2024-03-04 06:16 UTC, ashermancinelli commented
@dmitri-mcguckin @andrewgreenberg Andrew encouraged me to merge that student's PR tonight. If you'd like something different to happen with the repo, you all can let me know once you've agreed on it. I can revisit this work after that happens.

2024-03-04 06:23 UTC, dmitri-mcguckin commented
I got enough context from the slack conversations on what you intend to do and am fine with it. I only wanted to keep this PR if the plan was to adapt and clean what exists.

Now that this PR is committed to the tree, I simply recommend wiping away main sooner rather than later, (via a new commit, no squashing), so we don't have any artifact code. That way you can use what's in the commit tree if you still need a reference.

Then find a nice python project template to use somewhere. I have one I made for my personal python projects if you're interested. Can link when I'm not on mobile.


Just curious, do you need any of the other branches as well? If not- I can cull those as well.

Almost time for spring cleaning.